DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS act;
DROP TABLE IF EXISTS gamestate;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS item;


CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  posX INTEGER NOT NULL DEFAULT 0,
  posY INTEGER NOT NULL DEFAULT 0,
  health INTEGER NOT NULL DEFAULT 10,
  max_health INTEGER NOT NULL DEFAULT 10,
  action_points INTEGER NOT NULL DEFAULT 5,
  room INTEGER NOT NULL DEFAULT 3

);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE act (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  turn_action TEXT NOT NULL,
  turn_description TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE gamestate (
  turn INTEGER PRIMARY KEY DEFAULT 1,
  gameloops INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE location (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT NOT NULL,
  posX INTEGER NOT NULL DEFAULT 0,
  posY INTEGER NOT NULL DEFAULT 0

);

CREATE TABLE item (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  full_name TEXT NOT NULL,
  health INTEGER NOT NULL DEFAULT 0,
  action TEXT NOT NULL,
  armorType TEXT NOT NULL DEFAULT "None",
  ownerID INTEGER NOT NULL DEFAULT 0,
  onGround BOOLEAN NOT NULL DEFAULT 1

);

